apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: f9283a8240fc15f75f88691fb7ce432c163259e4ac2731544a928e54626d1dd6
    cni.projectcalico.org/podIP: 10.233.71.30/32
    cni.projectcalico.org/podIPs: 10.233.71.30/32
  creationTimestamp: "2024-04-08T01:10:06Z"
  labels:
    run: testpod
  name: testpod
  namespace: default
  resourceVersion: "931609"
  uid: cfb55656-3e45-47ca-9ced-1fad6bd2722c
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: testpod
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pjjrg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: pod-viewer
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-pjjrg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-08T01:10:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-08T01:10:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-08T01:10:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-08T01:10:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6ad7764518e2c6f8e694e1e766f1eea1377b68bc871543cd8054e2b67a2f1e90
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:6db391d1c0cfb30588ba0bf72ea999404f2764febf0f1f196acd5867ac7efa7e
    lastState: {}
    name: testpod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-08T01:10:13Z"
  hostIP: 192.168.10.40
  phase: Running
  podIP: 10.233.71.30
  podIPs:
  - ip: 10.233.71.30
  qosClass: BestEffort
  startTime: "2024-04-08T01:10:06Z"
